### ISSUE TITLE
Hello, what are the version numbers of the various libraries you use in python? Can you provide them? Thank you very much.

### ISSUE THREAD

**Issue by lmd123123** [muntasirhsn/CNN-LSTM-model-for-energy-usage-forecasting#1]

**Comment by muntasirhsn** [comment]
Hi, 
Due to some updates in Keras, the file may not run properly in Google colab. A new notebook file "CNN-LSTM_univariate_multistep_output_github_2023.ipynb" has been added. Please run the notebook in colab and let me know if there is an issue.  The versions of the libraries (included in the new notebook) are:

numpy version:  1.23.5
tensorflow version:  2.14.0
pandas version:  1.5.3
scikit-learn version:  1.2.2
keras version:  2.14.0
